### ISSUE TITLE
Woohoo! Issues!

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/opensource.scilifelab-theme#1]
Tack @robinandeer!

**Comment by guillermo-carrasco** [comment]
:sweat_smile:

**Comment by robinandeer** [comment]
Väl bekomme! (as we say in Sweden)

... and when you merge ewels/opensource.scilifelab-theme#5, GitHub should auto-close even this cross-repo issue: SciLifeLab/opensource.scilifelab#2 ^^

**Comment by ewels** [comment]
Not if I delete that repo first ;)
